use_frameworks!

platform :ios, '10.0'

target 'PageTransitionExample' do
  pod 'PageTransition', :path => '../'

#  target 'PageTransitionExampleUITests' do
#    inherit! :search_paths
#
#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
#
#  end
end


target 'PageTransitionExampleUITests' do
  pod 'PageTransition', :path => '../'
  pod 'iOSSnapshotTestCase' , '~> 6.2'
end
