use_frameworks!

target 'PageTransition_Example' do
  pod 'PageTransition', :path => '../'

  target 'PageTransition_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
