osx_image: xcode12.0
language: swift
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -allowProvisioningUpdates -enableCodeCoverage YES -workspace       Example/PageTransition.xcworkspace -scheme PageTransitionExample -sdiphonesimulator13.5        ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
