osx_image: xcode12.0
language: swift
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods
- pod install --project-directory=Example
script:
- set -o pipefail &&
  xcodebuild test
  -enableCodeCoverage YES
  -workspace Example/PageTransitionExample.xcworkspace
  -scheme PageTransitionExample
  -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=13.5'
  ONLY_ACTIVE_ARCH=NO
  CODE_SIGN_IDENTITY=""
  CODE_SIGNING_REQUIRED="NO"
  CODE_SIGN_ENTITLEMENTS=""
  CODE_SIGNING_ALLOWED="NO"
  | xcpretty
- pod lib lint
